// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TutorTrackApi.Data;

#nullable disable

namespace TutorTrackApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260903195253_AddUserAuthentication")]
    partial class AddUserAuthentication
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("IncomeType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("IncomeTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 9, 3, 19, 52, 52, 955, DateTimeKind.Utc).AddTicks(591),
                            Key = "TUTORING"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 9, 3, 19, 52, 52, 955, DateTimeKind.Utc).AddTicks(592),
                            Key = "OTHER"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 9, 3, 19, 52, 52, 955, DateTimeKind.Utc).AddTicks(593),
                            Key = "SALARY"
                        });
                });

            modelBuilder.Entity("TutorTrackApi.Models.IncomeEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Amount")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double?>("Hours")
                        .HasColumnType("REAL");

                    b.Property<int>("IncomeTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("StudentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IncomeTypeId");

                    b.HasIndex("StudentId");

                    b.ToTable("IncomeEntries");
                });

            modelBuilder.Entity("TutorTrackApi.Models.IncomeGoal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("AnnualAmount")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<double>("MonthlyAmount")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("IncomeGoals");
                });

            modelBuilder.Entity("TutorTrackApi.Models.IncomeTypeTranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("IncomeTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LanguageId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.HasIndex("IncomeTypeId", "LanguageId")
                        .IsUnique();

                    b.ToTable("IncomeTypeTranslations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 9, 3, 19, 52, 52, 955, DateTimeKind.Utc).AddTicks(609),
                            IncomeTypeId = 1,
                            LanguageId = 1,
                            Name = "Ripetizioni"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 9, 3, 19, 52, 52, 955, DateTimeKind.Utc).AddTicks(611),
                            IncomeTypeId = 1,
                            LanguageId = 2,
                            Name = "Tutoring"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 9, 3, 19, 52, 52, 955, DateTimeKind.Utc).AddTicks(613),
                            IncomeTypeId = 3,
                            LanguageId = 1,
                            Name = "Altro"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 9, 3, 19, 52, 52, 955, DateTimeKind.Utc).AddTicks(613),
                            IncomeTypeId = 3,
                            LanguageId = 2,
                            Name = "Other"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 9, 3, 19, 52, 52, 955, DateTimeKind.Utc).AddTicks(614),
                            IncomeTypeId = 4,
                            LanguageId = 1,
                            Name = "Stipendio"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2026, 9, 3, 19, 52, 52, 955, DateTimeKind.Utc).AddTicks(615),
                            IncomeTypeId = 4,
                            LanguageId = 2,
                            Name = "Salary"
                        });
                });

            modelBuilder.Entity("TutorTrackApi.Models.Language", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Languages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "it",
                            CreatedAt = new DateTime(2026, 9, 3, 19, 52, 52, 955, DateTimeKind.Utc).AddTicks(507),
                            Name = "Italiano"
                        },
                        new
                        {
                            Id = 2,
                            Code = "en",
                            CreatedAt = new DateTime(2026, 9, 3, 19, 52, 52, 955, DateTimeKind.Utc).AddTicks(510),
                            Name = "English"
                        });
                });

            modelBuilder.Entity("TutorTrackApi.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("TutorTrackApi.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TutorTrackApi.Models.IncomeEntry", b =>
                {
                    b.HasOne("IncomeType", "IncomeType")
                        .WithMany("Entries")
                        .HasForeignKey("IncomeTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TutorTrackApi.Models.Student", "Student")
                        .WithMany("Entries")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("IncomeType");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("TutorTrackApi.Models.IncomeTypeTranslation", b =>
                {
                    b.HasOne("IncomeType", "IncomeType")
                        .WithMany("Translations")
                        .HasForeignKey("IncomeTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TutorTrackApi.Models.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IncomeType");

                    b.Navigation("Language");
                });

            modelBuilder.Entity("IncomeType", b =>
                {
                    b.Navigation("Entries");

                    b.Navigation("Translations");
                });

            modelBuilder.Entity("TutorTrackApi.Models.Student", b =>
                {
                    b.Navigation("Entries");
                });
#pragma warning restore 612, 618
        }
    }
}
