// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TutorTrackApi.Data;

#nullable disable

namespace TutorTrackApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("IncomeType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("IncomeTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 4, 14, 14, 37, 52, 607, DateTimeKind.Utc).AddTicks(2083),
                            Key = "TUTORING"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 4, 14, 14, 37, 52, 607, DateTimeKind.Utc).AddTicks(2084),
                            Key = "OTHER"
                        });
                });

            modelBuilder.Entity("TutorTrackApi.Models.IncomeEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Amount")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double?>("Hours")
                        .HasColumnType("REAL");

                    b.Property<int>("IncomeTypeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IncomeTypeId");

                    b.ToTable("IncomeEntries");
                });

            modelBuilder.Entity("TutorTrackApi.Models.IncomeTypeTranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("IncomeTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LanguageId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.HasIndex("IncomeTypeId", "LanguageId")
                        .IsUnique();

                    b.ToTable("IncomeTypeTranslations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 4, 14, 14, 37, 52, 607, DateTimeKind.Utc).AddTicks(2098),
                            IncomeTypeId = 1,
                            LanguageId = 1,
                            Name = "Ripetizioni"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 4, 14, 14, 37, 52, 607, DateTimeKind.Utc).AddTicks(2101),
                            IncomeTypeId = 1,
                            LanguageId = 2,
                            Name = "Tutoring"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 4, 14, 14, 37, 52, 607, DateTimeKind.Utc).AddTicks(2102),
                            IncomeTypeId = 2,
                            LanguageId = 1,
                            Name = "Traslochi"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 4, 14, 14, 37, 52, 607, DateTimeKind.Utc).AddTicks(2103),
                            IncomeTypeId = 2,
                            LanguageId = 2,
                            Name = "Moving"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 4, 14, 14, 37, 52, 607, DateTimeKind.Utc).AddTicks(2104),
                            IncomeTypeId = 3,
                            LanguageId = 1,
                            Name = "Altro"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 4, 14, 14, 37, 52, 607, DateTimeKind.Utc).AddTicks(2105),
                            IncomeTypeId = 3,
                            LanguageId = 2,
                            Name = "Other"
                        });
                });

            modelBuilder.Entity("TutorTrackApi.Models.Language", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Languages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "it",
                            CreatedAt = new DateTime(2026, 4, 14, 14, 37, 52, 607, DateTimeKind.Utc).AddTicks(2002),
                            Name = "Italiano"
                        },
                        new
                        {
                            Id = 2,
                            Code = "en",
                            CreatedAt = new DateTime(2026, 4, 14, 14, 37, 52, 607, DateTimeKind.Utc).AddTicks(2005),
                            Name = "English"
                        });
                });

            modelBuilder.Entity("TutorTrackApi.Models.IncomeEntry", b =>
                {
                    b.HasOne("IncomeType", "IncomeType")
                        .WithMany("Entries")
                        .HasForeignKey("IncomeTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IncomeType");
                });

            modelBuilder.Entity("TutorTrackApi.Models.IncomeTypeTranslation", b =>
                {
                    b.HasOne("IncomeType", "IncomeType")
                        .WithMany("Translations")
                        .HasForeignKey("IncomeTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TutorTrackApi.Models.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IncomeType");

                    b.Navigation("Language");
                });

            modelBuilder.Entity("IncomeType", b =>
                {
                    b.Navigation("Entries");

                    b.Navigation("Translations");
                });
#pragma warning restore 612, 618
        }
    }
}
